-- 1. Market health overview (neighborhood × month)
CREATE OR REPLACE VIEW vw_market_health AS
SELECT
    n.CITY,
    n.NEIGHBOURHOOD_CLEANSED,
    n.MONTH,
    n.LISTING_COUNT,
    n.REVIEW_COUNT,
    n.AVG_REVIEWS_PER_MONTH,
    n.AVG_AVAILABILITY_365,
    n.AVG_ESTIMATED_OCCUPANCY,
    n.MEDIAN_INCOME,
    -- Income tier segmentation
    NTILE(3) OVER (PARTITION BY n.CITY ORDER BY n.MEDIAN_INCOME) AS income_tile,
    CASE
        WHEN NTILE(3) OVER (PARTITION BY n.CITY ORDER BY n.MEDIAN_INCOME) = 1 THEN 'Low'
        WHEN NTILE(3) OVER (PARTITION BY n.CITY ORDER BY n.MEDIAN_INCOME) = 2 THEN 'Mid'
        ELSE 'High'
    END AS INCOME_GROUP
FROM FACT_NEIGHBORHOOD_ALL n;


-- 2. Price and supply trends by room type and month
CREATE OR REPLACE VIEW vw_price_supply_trends AS
SELECT
    CITY,
    NEIGHBOURHOOD_CLEANSED,
    MONTH,
    ROOM_TYPE,
    COUNT(LISTING_ID)                   AS LISTING_COUNT,
    MEDIAN(ESTIMATED_REVENUE_L365D)     AS MEDIAN_REVENUE,
    AVG(ESTIMATED_REVENUE_L365D)        AS AVG_REVENUE,
    AVG(ESTIMATED_OCCUPANCY_L365D)      AS AVG_OCCUPANCY,
    AVG(AVAILABILITY_365)               AS AVG_AVAILABILITY,
    SUM(NUMBER_OF_REVIEWS)              AS TOTAL_REVIEWS,

    -- Month-over-month listing growth
    COUNT(LISTING_ID) - LAG(COUNT(LISTING_ID)) OVER (
        PARTITION BY CITY, NEIGHBOURHOOD_CLEANSED, ROOM_TYPE
        ORDER BY MONTH
    ) AS MOM_LISTING_CHANGE,

    (COUNT(LISTING_ID) - LAG(COUNT(LISTING_ID)) OVER (
        PARTITION BY CITY, NEIGHBOURHOOD_CLEANSED, ROOM_TYPE
        ORDER BY MONTH
    )) / NULLIF(LAG(COUNT(LISTING_ID)) OVER (
        PARTITION BY CITY, NEIGHBOURHOOD_CLEANSED, ROOM_TYPE
        ORDER BY MONTH
    ), 0)                               AS MOM_LISTING_GROWTH_RATE

FROM FACT_LISTING_ALL
GROUP BY CITY, NEIGHBOURHOOD_CLEANSED, MONTH, ROOM_TYPE;


-- 3. Room type breakdown by income group
CREATE OR REPLACE VIEW vw_roomtype_by_income AS
SELECT
    l.CITY,
    l.NEIGHBOURHOOD_CLEANSED,
    l.ROOM_TYPE,
    COUNT(l.LISTING_ID)                  AS LISTING_COUNT,
    AVG(l.ESTIMATED_OCCUPANCY_L365D)     AS AVG_OCCUPANCY,
    AVG(l.ESTIMATED_REVENUE_L365D)       AS AVG_REVENUE,
    AVG(l.REVIEWS_PER_MONTH)             AS AVG_REVIEWS,
    n.MEDIAN_INCOME,
    CASE
        WHEN NTILE(3) OVER (PARTITION BY l.CITY ORDER BY n.MEDIAN_INCOME) = 1 THEN 'Low'
        WHEN NTILE(3) OVER (PARTITION BY l.CITY ORDER BY n.MEDIAN_INCOME) = 2 THEN 'Mid'
        ELSE 'High'
    END AS INCOME_GROUP

FROM FACT_LISTING_ALL l
LEFT JOIN (
    SELECT CITY, NEIGHBOURHOOD_CLEANSED, MEDIAN_INCOME
    FROM FACT_NEIGHBORHOOD_ALL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CITY, NEIGHBOURHOOD_CLEANSED
        ORDER BY MONTH DESC
    ) = 1
) n ON l.CITY = n.CITY
   AND l.NEIGHBOURHOOD_CLEANSED = n.NEIGHBOURHOOD_CLEANSED

GROUP BY
    l.CITY,
    l.NEIGHBOURHOOD_CLEANSED,
    l.ROOM_TYPE,
    n.MEDIAN_INCOME;


-- 4. Income tier comparison (aggregated by city × income group × month)
CREATE OR REPLACE VIEW vw_income_tier_comparison AS
WITH income_groups AS (
    SELECT
        CITY,
        NEIGHBOURHOOD_CLEANSED,
        MONTH,
        LISTING_COUNT,
        REVIEW_COUNT,
        AVG_ESTIMATED_OCCUPANCY,
        MEDIAN_INCOME,
        CASE
            WHEN NTILE(3) OVER (PARTITION BY CITY ORDER BY MEDIAN_INCOME) = 1 THEN 'Low'
            WHEN NTILE(3) OVER (PARTITION BY CITY ORDER BY MEDIAN_INCOME) = 2 THEN 'Mid'
            ELSE 'High'
        END AS INCOME_GROUP
    FROM FACT_NEIGHBORHOOD_ALL
)
SELECT
    CITY,
    INCOME_GROUP,
    MONTH,
    AVG(MEDIAN_INCOME)           AS AVG_MEDIAN_INCOME,
    SUM(LISTING_COUNT)           AS TOTAL_LISTINGS,
    SUM(REVIEW_COUNT)            AS TOTAL_REVIEWS,
    AVG(AVG_ESTIMATED_OCCUPANCY) AS AVG_OCCUPANCY
FROM income_groups
GROUP BY CITY, INCOME_GROUP, MONTH;


-- 5. Host concentration analysis per neighborhood
CREATE OR REPLACE VIEW vw_host_concentration AS
SELECT
    h.CITY,
    h.NEIGHBOURHOOD_CLEANSED,
    h.HOST_COUNT,
    h.TOTAL_LISTINGS,
    h.AVG_LISTINGS_PER_HOST,
    h.LARGEST_HOST_SIZE,

    -- Share of market held by largest host
    h.LARGEST_HOST_SIZE / NULLIF(h.TOTAL_LISTINGS, 0) AS LARGEST_HOST_SHARE,

    -- Concentration risk flag
    CASE
        WHEN h.LARGEST_HOST_SIZE / NULLIF(h.TOTAL_LISTINGS, 0) > 0.20 THEN 'High'
        WHEN h.LARGEST_HOST_SIZE / NULLIF(h.TOTAL_LISTINGS, 0) > 0.10 THEN 'Medium'
        ELSE 'Low'
    END AS CONCENTRATION_RISK,

    -- Join income group from neighborhood fact
    n.MEDIAN_INCOME,
    CASE
        WHEN NTILE(3) OVER (PARTITION BY h.CITY ORDER BY n.MEDIAN_INCOME) = 1 THEN 'Low'
        WHEN NTILE(3) OVER (PARTITION BY h.CITY ORDER BY n.MEDIAN_INCOME) = 2 THEN 'Mid'
        ELSE 'High'
    END AS INCOME_GROUP

FROM FACT_HOST_SUMMARY h
LEFT JOIN (
    -- Get one income value per neighbourhood (latest month)
    SELECT CITY, NEIGHBOURHOOD_CLEANSED, MEDIAN_INCOME
    FROM FACT_NEIGHBORHOOD_ALL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CITY, NEIGHBOURHOOD_CLEANSED
        ORDER BY MONTH DESC
    ) = 1
) n ON h.CITY = n.CITY
    AND h.NEIGHBOURHOOD_CLEANSED = n.NEIGHBOURHOOD_CLEANSED;


-- 6. Saturation risk assessment (latest snapshot)
CREATE OR REPLACE VIEW vw_saturation_risk AS
WITH latest AS (
    SELECT *
    FROM FACT_NEIGHBORHOOD_ALL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CITY, NEIGHBOURHOOD_CLEANSED
        ORDER BY MONTH DESC
    ) = 1
),
city_avg AS (
    SELECT CITY, AVG(REVIEW_COUNT) AS CITY_AVG_REVIEWS
    FROM latest
    GROUP BY CITY
)
SELECT
    l.CITY,
    l.NEIGHBOURHOOD_CLEANSED,
    l.LISTING_COUNT,
    l.REVIEW_COUNT,
    l.AVG_ESTIMATED_OCCUPANCY,
    l.MEDIAN_INCOME,
    CASE
        WHEN NTILE(3) OVER (PARTITION BY l.CITY ORDER BY l.MEDIAN_INCOME) = 1 THEN 'Low'
        WHEN NTILE(3) OVER (PARTITION BY l.CITY ORDER BY l.MEDIAN_INCOME) = 2 THEN 'Mid'
        ELSE 'High'
    END AS INCOME_GROUP,

    -- Saturation: many listings but low demand relative to city average
    CASE
        WHEN l.LISTING_COUNT > AVG(l.LISTING_COUNT) OVER (PARTITION BY l.CITY)
         AND l.REVIEW_COUNT < c.CITY_AVG_REVIEWS
        THEN 'High Risk'
        WHEN l.LISTING_COUNT > AVG(l.LISTING_COUNT) OVER (PARTITION BY l.CITY)
        THEN 'Medium Risk'
        ELSE 'Low Risk'
    END AS SATURATION_RISK

FROM latest l
JOIN city_avg c ON l.CITY = c.CITY;
