CREATE DATABASE AIRBNB_PIPELINE;
CREATE SCHEMA AIRBNB_PIPELINE.GOLD;
CREATE WAREHOUSE AIRBNB_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

USE WAREHOUSE AIRBNB_WH;
USE DATABASE AIRBNB_PIPELINE;
USE SCHEMA GOLD;

CREATE OR REPLACE STAGE airbnb_stage;

CREATE OR REPLACE FILE FORMAT parquet_format
TYPE = PARQUET;


CREATE OR REPLACE TABLE FACT_NEIGHBORHOOD_ALL AS

SELECT 
'LA' AS CITY,
*
FROM FACT_NEIGHBORHOOD_LA

UNION ALL

SELECT 
'NYC' AS CITY,
*
FROM FACT_NEIGHBORHOOD_NYC

UNION ALL

SELECT 
'PORTLAND' AS CITY,
*
FROM FACT_NEIGHBORHOOD_PORTLAND

UNION ALL

SELECT 
'SF' AS CITY,
*
FROM FACT_NEIGHBORHOOD_SF;



SELECT
COUNT(*) AS total_rows,

ROUND(COUNT_IF(ACCOMMODATES IS NULL)/COUNT(*)*100,2) AS pct_null_accommodates,
ROUND(COUNT_IF(AVAILABILITY_365 IS NULL)/COUNT(*)*100,2) AS pct_null_availability_365,
ROUND(COUNT_IF(ESTIMATED_OCCUPANCY_L365D IS NULL)/COUNT(*)*100,2) AS pct_null_estimated_occupancy,
ROUND(COUNT_IF(ESTIMATED_REVENUE_L365D IS NULL)/COUNT(*)*100,2) AS pct_null_estimated_revenue,
ROUND(COUNT_IF(LISTING_ID IS NULL)/COUNT(*)*100,2) AS pct_null_listing_id,
ROUND(COUNT_IF(MONTH IS NULL)/COUNT(*)*100,2) AS pct_null_month,
ROUND(COUNT_IF(NEIGHBOURHOOD_CLEANSED IS NULL)/COUNT(*)*100,2) AS pct_null_neighbourhood,
ROUND(COUNT_IF(NUMBER_OF_REVIEWS IS NULL)/COUNT(*)*100,2) AS pct_null_number_of_reviews,
ROUND(COUNT_IF(REVIEWS_PER_MONTH IS NULL)/COUNT(*)*100,2) AS pct_null_reviews_per_month,
ROUND(COUNT_IF(ROOM_TYPE IS NULL)/COUNT(*)*100,2) AS pct_null_room_type

FROM FACT_LISTING_SF;



CREATE OR REPLACE TABLE FACT_LISTING_ALL AS

SELECT 
'LA' AS CITY,
*
FROM FACT_LISTING_LA

UNION ALL

SELECT 
'NYC' AS CITY,
*
FROM FACT_LISTING_NYC

UNION ALL

SELECT 
'PORTLAND' AS CITY,
*
FROM FACT_LISTING_PORTLAND

UNION ALL

SELECT 
'SF' AS CITY,
*
FROM FACT_LISTING_SF;


SELECT
MONTH,
COUNT(*)
FROM FACT_LISTING_ALL
GROUP BY MONTH
ORDER BY MONTH;

SELECT
COUNT(*) AS total_rows,
COUNT(DISTINCT LISTING_ID || '-' || MONTH) AS unique_rows
FROM FACT_LISTING_ALL;




SELECT
COUNT(*) AS TOTAL_ROWS,

SUM(CASE WHEN CITY IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_CITY,

SUM(CASE WHEN NEIGHBOURHOOD_CLEANSED IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_NEIGHBORHOOD,

SUM(CASE WHEN MONTH IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_MONTH,

SUM(CASE WHEN LISTING_COUNT IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_LISTING_COUNT,

SUM(CASE WHEN REVIEW_COUNT IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_REVIEW_COUNT,

SUM(CASE WHEN AVG_AVAILABILITY_365 IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_AVAILABILITY,

SUM(CASE WHEN AVG_ESTIMATED_OCCUPANCY IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_OCCUPANCY,

SUM(CASE WHEN AVG_REVIEWS_PER_MONTH IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_REVIEWS_PER_MONTH,

SUM(CASE WHEN MEDIAN_INCOME IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_INCOME

FROM FACT_NEIGHBORHOOD_ALL;



SELECT
CITY,
NEIGHBOURHOOD_CLEANSED,
MONTH,
COUNT(*)
FROM FACT_NEIGHBORHOOD_ALL
GROUP BY CITY, NEIGHBOURHOOD_CLEANSED, MONTH
HAVING COUNT(*) > 1;



SELECT
CITY,
COUNT(*) AS ROW_COUNT
FROM FACT_NEIGHBORHOOD_ALL
GROUP BY CITY;



SELECT
MIN(AVG_ESTIMATED_OCCUPANCY),
MAX(AVG_ESTIMATED_OCCUPANCY)
FROM FACT_NEIGHBORHOOD_ALL;


SELECT
COUNT(*) AS TOTAL_ROWS,

SUM(CASE WHEN CITY IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_CITY,

SUM(CASE WHEN NEIGHBOURHOOD_CLEANSED IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_NEIGHBORHOOD,

SUM(CASE WHEN HOST_COUNT IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_HOST_COUNT,

SUM(CASE WHEN TOTAL_LISTINGS IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_TOTAL_LISTINGS,

SUM(CASE WHEN AVG_LISTINGS_PER_HOST IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_AVG_LISTINGS,

SUM(CASE WHEN LARGEST_HOST_SIZE IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS PCT_NULL_LARGEST_HOST

FROM FACT_HOST_SUMMARY;



SELECT
CITY,
NEIGHBOURHOOD_CLEANSED,
COUNT(*)
FROM FACT_HOST_SUMMARY
GROUP BY CITY, NEIGHBOURHOOD_CLEANSED
HAVING COUNT(*) > 1;




SELECT
MIN(HOST_COUNT),
MAX(HOST_COUNT),
MIN(TOTAL_LISTINGS),
MAX(TOTAL_LISTINGS)
FROM FACT_HOST_SUMMARY;




SELECT
MIN(AVG_LISTINGS_PER_HOST),
MAX(AVG_LISTINGS_PER_HOST)
FROM FACT_HOST_SUMMARY;



SELECT
CITY,
COUNT(*) AS NEIGHBORHOODS
FROM FACT_HOST_SUMMARY
GROUP BY CITY;



SELECT
CITY,
NEIGHBOURHOOD_CLEANSED,
AVG_LISTINGS_PER_HOST,
TOTAL_LISTINGS / HOST_COUNT AS CALCULATED
FROM FACT_HOST_SUMMARY
LIMIT 20;




